### ISSUE TITLE
Implementar Graph-tools-vol2

### ISSUE THREAD

**Issue by WalterHenri** [TheBestRoosterBr/Rotas-da-UFS#4]
Implementar uma biblioteca de buscas com visitor para achar o melhor caminho possível usando os algoritmos de busca

**Comment by j0ng4b** [comment]
Como não sei se vai ter pull request então já vou fazer uma revisãozinha...

***
DFS não é o nome mais adequado pra essa classe porque teoricamente ela implementa mais de uma algoritmo de busca e “DFS” já é um algoritmo de busca, porque um algoritmo de busca implementa outros?

https://github.com/TheBestRoosterBr/Rotas-da-UFS/blob/94dd70e5403a566f656b32fd2db2abb1a2039aad/backend/graph-tools-vol2/dfs.py#L7-L20

***

Com todo respeito mas isso é a coisa mais feia que já vi em um código Python 😓
https://github.com/TheBestRoosterBr/Rotas-da-UFS/blob/94dd70e5403a566f656b32fd2db2abb1a2039aad/backend/graph-tools-vol2/grafo.py#L2-L8

Eu não sei nem se isso funciona porque não lembro se tem overload de função em Python de qualquer forma é muito feio 😓, desculpa é porque realmente é feio, tem maneiras mais simples de fazer isso tipo:
```python
    def __init__(self, estado=[], transicoes=[]):
        # Resto do código
```

***

Sugiro que troque o nome da pasta da graph-tool-v2 porque isso não vai ser legal na hora de importar, por exemplo:
```python
# Muito feio e não parece certo.
from graph-tool-v2 import DFS
``` 

***

Um pouco de preferência pessoal... “Escrever código sem autocomplete é horroroso”, mas escrever código com nomes em português é ainda pior 🤢.

**Comment by j0ng4b** [comment]
Nada contra nem é nada pessoal... 😔
